case_name = "john+sally"
description = "This example reproduces the case of John and Sally, discussed by Eric Sajdak. This case can be used to compare the heuristic strategy of surfing a tax bracket for performing Roth conversions to a solution optimized by linear programming. The former is a good approach when one assumes fixed rates. When rates are varying, and the market drops, an optimized solution shows that it is sometime advantageous to convert above the target tax bracket. File 'HFP_john+sally.xlsx' contains wages and contributions associated with this case. Run this case with different rates to see the effects on Roth conversions."

[basic_info]
status = "married"
names = [ "John", "Sally",]
date_of_birth = [ "1963-01-15", "1963-01-15",]
life_expectancy = [ 92, 92,]
start_date = "2026-01-01"

[savings_assets]
taxable_savings_balances = [ 200.0, 200.0,]
tax_deferred_savings_balances = [ 750.0, 750.0,]
tax_free_savings_balances = [ 50.0, 50.0,]
beneficiary_fractions = [ 1.0, 1.0, 1.0,]
spousal_surplus_deposit_fraction = 0.5

[household_financial_profile]
HFP_file_name = "HFP_john+sally.xlsx"

[fixed_income]
pension_monthly_amounts = [ 0, 0,]
pension_ages = [ 65.0, 65.0,]
pension_indexed = [ false, false,]
social_security_pia_amounts = [ 3000, 1800,]
social_security_ages = [ 67.0, 67.0,]

[rates_selection]
heirs_rate_on_tax_deferred_estate = 30.0
dividend_rate = 1.8000000000000003
obbba_expiration_year = 2032
method = "historical average"
from = 1990
to = 2023

[asset_allocation]
interpolation_method = "linear"
interpolation_center = 15.0
interpolation_width = 5.0
type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],], [ [ 60, 40, 0, 0,], [ 60, 40, 0, 0,],],]

[optimization_parameters]
spending_profile = "flat"
surviving_spouse_spending_percent = 60
objective = "maxBequest"

[solver_options]
netSpending = 100
maxRothConversion = 200
noRothConversions = "None"
startRothConversions = 2025
withMedicare = "loop"
solver = "HiGHS"
spendingSlack = 0
withSCLoop = true

[results]
default_plots = "today"
