"Plan Name" = "drawdown_comparison-1"
Description = "This is a case involving a single individual. Case is used for comparing with @hugcity's DrawdownCalc. For max bequest, it should yield $90,762, while an $80k net spending should leave $673,156 as a bequest."

["Basic Info"]
Status = "single"
Names = [ "Charles",]
"Birth year" = [ 1966,]
"Life expectancy" = [ 89,]
"Start date" = "2025-01-01"

[Assets]
"taxable savings balances" = [ 250.0,]
"tax-deferred savings balances" = [ 600.0,]
"tax-free savings balances" = [ 600.0,]

["Wages and Contributions"]
"Contributions file name" = "edited values"

["Fixed Income"]
"Pension amounts" = [ 0.0,]
"Pension ages" = [ 65,]
"Pension indexed" = [ true,]
"Social security amounts" = [ 36.0,]
"Social security ages" = [ 70,]

["Rates Selection"]
"Heirs rate on tax-deferred estate" = 0.0
"Long-term capital gain tax rate" = 0.0
"Dividend rate" = 0.0
"TCJA expiration year" = 2099
Method = "user"
Values = [ 6.5, 0.0, 0.0, 2.8,]
From = 1928
To = 2024

["Asset Allocation"]
"Interpolation method" = "s-curve"
"Interpolation center" = 15.0
"Interpolation width" = 5.0
Type = "individual"
generic = [ [ [ 100, 0, 0, 0,], [ 100, 0, 0, 0,],],]

["Optimization Parameters"]
"Spending profile" = "flat"
"Surviving spouse spending percent" = 60
Objective = "maxBequest"

["Solver Options"]
netSpending = 80.0
maxRothConversion = 50
startRothConversions = 2025
withMedicare = false
solver = "HiGHS"
spendingSlack = 0

[Results]
"Default plots" = "today"
