"Plan Name" = "kim+sam-bequest"
Description = "This is the case of Kim and Sam used as an example case for optimizing bequest and Roth conversions. No wages and contributions file is associated with this case."

["Basic Info"]
Status = "married"
Names = [ "Kim", "Sam",]
"Birth year" = [ 1966, 1967,]
"Birth month" = [ 1, 1,]
"Life expectancy" = [ 86, 89,]
"Start date" = "01-01"

[Assets]
"taxable savings balances" = [ 1000.0, 0.0,]
"tax-deferred savings balances" = [ 2000.0, 800.0,]
"tax-free savings balances" = [ 500.0, 25.0,]
"Beneficiary fractions" = [ 1, 1, 1,]
"Spousal surplus deposit fraction" = 0.5

["Wages and Contributions"]
"Contributions file name" = "kim+sam.xlsx"

["Fixed Income"]
"Pension amounts" = [ 0.0, 0.0,]
"Pension ages" = [ 65, 65,]
"Pension indexed" = [ false, false,]
"Social security PIA amounts" = [ 3750, 2083,]
"Social security ages" = [ 70, 68,]

["Rates Selection"]
"Heirs rate on tax-deferred estate" = 33.0
"Dividend rate" = 1.8
"OBBBA expiration year" = 2032
Method = "conservative"
From = 1922
To = 2023

["Asset Allocation"]
"Interpolation method" = "s-curve"
"Interpolation center" = 15
"Interpolation width" = 5
Type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 70, 30, 0, 0,],], [ [ 60, 40, 0, 0,], [ 70, 30, 0, 0,],],]

["Optimization Parameters"]
"Spending profile" = "smile"
"Smile dip" = 15
"Smile increase" = 12
"Smile delay" = 0
"Surviving spouse spending percent" = 60
Objective = "maxBequest"

["Solver Options"]
maxRothConversion = 300
netSpending = 180

[Results]
"Default plots" = "today"
