case_name = "jack+jill"
description = "This example aims to demonstrate some of Owl's capabilities. Jack and Jill are a married couple a few years from retirement. A Household Financial Profile called 'HFP_jack+jill.xlsx' is associated with this case. This case uses the historical rate sequence of 1969 as a test case for guiding spending amounts from a near worst-case historical scenario. This case also demonstrates that the optimal strategy for Roth conversions does not necessarily involve surfing a tax bracket.  \nA good exercise for learning Owl's capabilities is to duplicate this case and compare two scenarios: one with optimized Roth conversions and one without. Another possible exercise could involve comparing a historical retirement in 1969 vs. one taken in 1966. Or anything else you can think of..."

[basic_info]
status = "married"
names = [ "Jack", "Jill",]
date_of_birth = [ "1963-01-15", "1966-01-15",]
life_expectancy = [ 89, 92,]
start_date = "2026-01-01"

[savings_assets]
taxable_savings_balances = [ 90.5, 60.2,]
tax_deferred_savings_balances = [ 600.5, 150.0,]
tax_free_savings_balances = [ 70.6, 40.8,]
beneficiary_fractions = [ 1.0, 1.0, 1.0,]
spousal_surplus_deposit_fraction = 0.5

[household_financial_profile]
HFP_file_name = "HFP_jack+jill.xlsx"

[fixed_income]
pension_monthly_amounts = [ 0.0, 10.5,]
pension_ages = [ 65.0, 65.0,]
pension_indexed = [ false, false,]
social_security_pia_amounts = [ 2360, 1642,]
social_security_ages = [ 70.0, 62.083333333333336,]

[rates_selection]
heirs_rate_on_tax_deferred_estate = 30.0
dividend_rate = 1.7
obbba_expiration_year = 2032
method = "historical"
from = 1969
to = 2001

[asset_allocation]
interpolation_method = "s-curve"
interpolation_center = 15.0
interpolation_width = 5.0
type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 70, 30, 0, 0,],], [ [ 50, 50, 0, 0,], [ 70, 30, 0, 0,],],]

[optimization_parameters]
spending_profile = "smile"
surviving_spouse_spending_percent = 60
smile_dip = 15
smile_increase = 12
smile_delay = 0
objective = "maxSpending"

[solver_options]
maxRothConversion = 100
noRothConversions = "Jill"
startRothConversions = 2025
withMedicare = "loop"
bequest = 400
solver = "HiGHS"
spendingSlack = 0
withSCLoop = true

[results]
default_plots = "today"
