case_name = "kim+sam-spending"
description = "This is the case of Kim and Sam used as an example case for optimizing spending and Roth conversions. No wages and contributions is associated with this case."

[basic_info]
status = "married"
names = [ "Kim", "Sam",]
date_of_birth = [ "1967-01-15", "1968-01-15",]
life_expectancy = [ 86, 89,]
start_date = "2026-01-01"

[savings_assets]
taxable_savings_balances = [ 1000.0, 0.0,]
tax_deferred_savings_balances = [ 2000.0, 800.0,]
tax_free_savings_balances = [ 500.0, 25.0,]
beneficiary_fractions = [ 1.0, 1.0, 1.0,]
spousal_surplus_deposit_fraction = 0.5

[household_financial_profile]
HFP_file_name = "HFP_kim+sam.xlsx"

[fixed_income]
pension_monthly_amounts = [ 0, 0,]
pension_ages = [ 65.0, 65.0,]
pension_indexed = [ false, false,]
social_security_pia_amounts = [ 3750, 2083,]
social_security_ages = [ 70.0, 68.0,]

[rates_selection]
heirs_rate_on_tax_deferred_estate = 33.0
dividend_rate = 1.8000000000000003
obbba_expiration_year = 2032
method = "user"
values = [ 6.0, 4.0, 3.3000000000000003, 2.8000000000000003,]
from = 1928
to = 2024

[asset_allocation]
interpolation_method = "s-curve"
interpolation_center = 15.0
interpolation_width = 5.0
type = "individual"
generic = [ [ [ 60, 40, 0, 0,], [ 70, 30, 0, 0,],], [ [ 60, 40, 0, 0,], [ 70, 30, 0, 0,],],]

[optimization_parameters]
spending_profile = "smile"
surviving_spouse_spending_percent = 60
smile_dip = 15
smile_increase = 12
smile_delay = 0
objective = "maxSpending"

[solver_options]
maxRothConversion = 300
noRothConversions = "None"
startRothConversions = 2025
withMedicare = "loop"
bequest = 2000
solver = "HiGHS"
spendingSlack = 0
xorConstraints = true
withSCLoop = true

[results]
default_plots = "nominal"
