"Plan Name" = "Jon+Jane"
Description = "This case reproduces a similar case discussed a while back on i-orp. It involves Jon and Jane close to retirement, and assumes a base case of optimistic returns of 10% with an inflation of 3.5%. A wages and contributions file called 'jon+jane.xlsx' is associated with this case."

["Basic Info"]
Status = "married"
Names = [ "Jon", "Jane",]
"Date of birth" = [ "1966-01-15", "1969-01-15",]
"Life expectancy" = [ 92, 92,]
"Start date" = "2026-01-01"

[Assets]
"taxable savings balances" = [ 50.0, 0.0,]
"tax-deferred savings balances" = [ 900.0, 500.0,]
"tax-free savings balances" = [ 0.0, 50.0,]
"Beneficiary fractions" = [ 1.0, 1.0, 1.0,]
"Spousal surplus deposit fraction" = 0.0

["Household Financial Profile"]
"HFP file name" = "HFP_jon+jane.xlsx"

["Fixed Income"]
"Pension monthly amounts" = [ 0, 0,]
"Pension ages" = [ 65.0, 65.0,]
"Pension indexed" = [ false, false,]
"Social security PIA amounts" = [ 1750, 1750,]
"Social security ages" = [ 65.0, 65.0,]

["Rates Selection"]
"Heirs rate on tax-deferred estate" = 30.0
"Dividend rate" = 1.8000000000000003
"OBBBA expiration year" = 2032
Method = "user"
Values = [ 10.0, 6.0, 5.0, 3.5000000000000004,]
From = 1928
To = 2024

["Asset Allocation"]
"Interpolation method" = "linear"
"Interpolation center" = 15.0
"Interpolation width" = 5.0
Type = "individual"
generic = [ [ [ 100, 0, 0, 0,], [ 100, 0, 0, 0,],], [ [ 100, 0, 0, 0,], [ 100, 0, 0, 0,],],]

["Optimization Parameters"]
"Spending profile" = "flat"
"Surviving spouse spending percent" = 60
Objective = "maxSpending"

["Solver Options"]
maxRothConversion = 0.0
noRothConversions = "None"
startRothConversions = 2025
withMedicare = "loop"
bequest = 30.0
solver = "HiGHS"
spendingSlack = 0
xorConstraints = true
withSCLoop = true

[Results]
"Default plots" = "today"
