case_name = "Jon+Jane"
description = "This case reproduces a similar case discussed a while back on i-orp. It involves Jon and Jane close to retirement, and assumes a base case of optimistic returns of 10% with an inflation of 3.5%. A Household Financial Profile called 'HFP_jon+jane.xlsx' is associated with this case."

[basic_info]
status = "married"
names = [ "Jon", "Jane",]
date_of_birth = [ "1966-01-15", "1969-01-15",]
life_expectancy = [ 92, 92,]
start_date = "2026-01-01"

[savings_assets]
taxable_savings_balances = [ 50.0, 0.0,]
tax_deferred_savings_balances = [ 900.0, 500.0,]
tax_free_savings_balances = [ 0.0, 50.0,]
beneficiary_fractions = [ 1.0, 1.0, 1.0,]
spousal_surplus_deposit_fraction = 0.0

[household_financial_profile]
HFP_file_name = "HFP_jon+jane.xlsx"

[fixed_income]
pension_monthly_amounts = [ 0, 0,]
pension_ages = [ 65.0, 65.0,]
pension_indexed = [ false, false,]
social_security_pia_amounts = [ 1750, 1750,]
social_security_ages = [ 65.0, 65.0,]

[rates_selection]
heirs_rate_on_tax_deferred_estate = 30.0
dividend_rate = 1.8000000000000003
obbba_expiration_year = 2032
method = "user"
values = [ 10.0, 6.0, 5.0, 3.5000000000000004,]
from = 1928
to = 2024

[asset_allocation]
interpolation_method = "linear"
interpolation_center = 15.0
interpolation_width = 5.0
type = "individual"
generic = [ [ [ 100, 0, 0, 0,], [ 100, 0, 0, 0,],], [ [ 100, 0, 0, 0,], [ 100, 0, 0, 0,],],]

[optimization_parameters]
spending_profile = "flat"
surviving_spouse_spending_percent = 60
objective = "maxSpending"

[solver_options]
maxRothConversion = 0.0
noRothConversions = "None"
startRothConversions = 2025
withMedicare = "loop"
bequest = 30.0
solver = "HiGHS"
spendingSlack = 0
withSCLoop = true

[results]
default_plots = "today"
